services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES-USER=root
      - POSTGRES-PASSWORD=root
      - POSTGRES-DB=ny_taxi
    volumes:
      - "./nytaxi_postgres/:/var/lib/postgresql/data:rw"
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80
